### PR TITLE
[wip] adds circleci

### PR DESCRIPTION
**Pull request by whereismyjetpack**

### CODE REVIEW

**Comment by awead** [comment]
@whereismyjetpack Overall, looks fine. Maybe a two-commit PR would look good here. First commit removes all of Drone, the second commit adds CI. Also, are you rebasing? You shouldn't get commits like "Merge branch 'master' into preview/circle" if you rebase, and that commit would just go away and you've be left with only the changes you're applying.

**Comment by whereismyjetpack** [comment]
I knew i should have started over. I'll get to this as soon as I can.

**Comment by awead** [comment]
@whereismyjetpack When this happens, I squash all the commits I want to keep into one single commit in my local git repo (assuming you don't want to keep that history), then checkout a new branch off of master, and cherry-pick the squashed commit into the new branch.

**Comment by whereismyjetpack** [comment]
I've found some things I'd like to optimize. PR forthcoming

**Pull request closed without merging**
